// <auto-generated />
using System;
using EventPad.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EventPad.Context.Migrations.PgSql.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240229101950_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EventPad.Context.Entities.CashoutEventReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventAccountId")
                        .HasColumnType("integer");

                    b.Property<string>("RKTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventAccountId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("cashout_event_receipts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.CashoutReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RKTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("cashout_receipts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.DepositReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RKTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("deposit_receipts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("AdminId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MainPhoto")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventAccount", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EventId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.HasKey("EventId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("event_accounts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("event_photos", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EventTicketId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EventTicketId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("event_tickets", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.PurchaseReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SpecificEventId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificEventId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("purchase_receipts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.RefundReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("SpecificEventId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.Property<int>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecificEventId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.HasIndex("UserAccountId");

                    b.ToTable("refund_receipts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.SpecificEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime?>("DateTime")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<float?>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("Private")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("specific_events", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("SecondName")
                        .HasColumnType("text");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.UserAccount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<float>("Balance")
                        .HasColumnType("real");

                    b.HasKey("UserId");

                    b.HasIndex("AccountNumber")
                        .IsUnique();

                    b.ToTable("user_accounts", (string)null);
                });

            modelBuilder.Entity("EventPad.Context.Entities.CashoutEventReceipt", b =>
                {
                    b.HasOne("EventPad.Context.Entities.EventAccount", "Account")
                        .WithMany("Cashouts")
                        .HasForeignKey("EventAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPad.Context.Entities.User", "User")
                        .WithMany("CashoutEventReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventPad.Context.Entities.CashoutReceipt", b =>
                {
                    b.HasOne("EventPad.Context.Entities.UserAccount", "UserAccount")
                        .WithMany("Cashouts")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EventPad.Context.Entities.DepositReceipt", b =>
                {
                    b.HasOne("EventPad.Context.Entities.UserAccount", "UserAccount")
                        .WithMany("Deposits")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EventPad.Context.Entities.Event", b =>
                {
                    b.HasOne("EventPad.Context.Entities.User", "Admin")
                        .WithMany("Events")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPad.Context.Entities.EventAccount", "EventAccount")
                        .WithOne("Event")
                        .HasForeignKey("EventPad.Context.Entities.Event", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("EventAccount");
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventPhoto", b =>
                {
                    b.HasOne("EventPad.Context.Entities.Event", "Event")
                        .WithMany("Photos")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventTicket", b =>
                {
                    b.HasOne("EventPad.Context.Entities.SpecificEvent", "SpecificEvent")
                        .WithMany("Tickets")
                        .HasForeignKey("EventTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPad.Context.Entities.User", "User")
                        .WithMany("EventTickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificEvent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventPad.Context.Entities.PurchaseReceipt", b =>
                {
                    b.HasOne("EventPad.Context.Entities.SpecificEvent", "SpecificEvent")
                        .WithMany("Purchases")
                        .HasForeignKey("SpecificEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPad.Context.Entities.UserAccount", "UserAccount")
                        .WithMany("Purchases")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificEvent");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EventPad.Context.Entities.RefundReceipt", b =>
                {
                    b.HasOne("EventPad.Context.Entities.SpecificEvent", "SpecificEvent")
                        .WithMany("Refunds")
                        .HasForeignKey("SpecificEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventPad.Context.Entities.UserAccount", "UserAccount")
                        .WithMany("Refunds")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpecificEvent");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("EventPad.Context.Entities.SpecificEvent", b =>
                {
                    b.HasOne("EventPad.Context.Entities.Event", "Event")
                        .WithMany("SpecificEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPad.Context.Entities.User", b =>
                {
                    b.HasOne("EventPad.Context.Entities.UserAccount", "Account")
                        .WithOne("User")
                        .HasForeignKey("EventPad.Context.Entities.User", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EventPad.Context.Entities.Event", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("SpecificEvents");
                });

            modelBuilder.Entity("EventPad.Context.Entities.EventAccount", b =>
                {
                    b.Navigation("Cashouts");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventPad.Context.Entities.SpecificEvent", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Refunds");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventPad.Context.Entities.User", b =>
                {
                    b.Navigation("CashoutEventReceipts");

                    b.Navigation("EventTickets");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventPad.Context.Entities.UserAccount", b =>
                {
                    b.Navigation("Cashouts");

                    b.Navigation("Deposits");

                    b.Navigation("Purchases");

                    b.Navigation("Refunds");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
